services:
  database:
    build:
      context: .
      dockerfile: ./packages/database/Dockerfile
    environment:
      - DATABASE_URL=http://localhost

  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
    depends_on:
      - database
  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - VITE_SERVER_URL=http://localhost:3000
    depends_on:
      - database
      - server